services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: food-review-app
    container_name: food-review-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
      - public_data:/var/www/html/public
      - /var/www/html/vendor
    networks:
      - food-review-network

  nginx:
    image: nginx:alpine
    container_name: food-review-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - public_data:/var/www/html/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./storage:/var/www/html/storage
    networks:
      - food-review-network
    depends_on:
      - app

volumes:
  public_data:

networks:
  food-review-network:
    driver: bridge
